/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ユーザーログイン
         * @description Emailとパスワードでログインし、JWTトークンを発行します
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @example taro@example.com
                         */
                        email: string;
                        /** @example password123 */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description ログイン成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /**
                             * @description JWT Access Token
                             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                             */
                            token: string;
                        };
                    };
                };
                /** @description バリデーションエラー - 入力形式が正しくありません */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success: boolean;
                            /** @example Authentication failed */
                            message: string;
                        };
                    };
                };
                /** @description 認証失敗 - メールアドレスまたはパスワードが間違っています */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success: boolean;
                            /** @example Authentication failed */
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ユーザー一覧取得
         * @description 削除されていないユーザーの一覧を返します（パスワードはマスクされます）
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 一覧取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example 2 */
                            count: number;
                            users: {
                                /** @example 1 */
                                id: string;
                                /** @example 山田 太郎 */
                                name: string;
                                /** @example ヤマダ タロウ */
                                kana: string;
                                /**
                                 * Format: email
                                 * @example taro@example.com
                                 */
                                email: string;
                                /** @example ********** */
                                password: string;
                                /** @example 2024-01-01T10:00:00.000Z */
                                createdAt: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/todos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * TODO一覧取得
         * @description ハードコードされたモックデータのTODO一覧を返します
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 一覧取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example 3 */
                            count: number;
                            todos: {
                                /** @example 1 */
                                id: string;
                                /** @example Vue.jsを学ぶ */
                                title: string;
                                /** @example false */
                                completed: boolean;
                                /** @example 2024-01-01T10:00:00Z */
                                createdAt: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * TODO追加
         * @description 新しいTODOを作成します（モックのため永続化されません）
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example 新しいタスク */
                        title: string;
                    };
                };
            };
            responses: {
                /** @description 作成成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            todo: {
                                /** @example 1 */
                                id: string;
                                /** @example Vue.jsを学ぶ */
                                title: string;
                                /** @example false */
                                completed: boolean;
                                /** @example 2024-01-01T10:00:00Z */
                                createdAt: string;
                            };
                        };
                    };
                };
                /** @description バリデーションエラー */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success: boolean;
                            /** @example Todo not found */
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/todos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * TODO更新
         * @description 指定IDのTODOを更新します（モックのため永続化されません）
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example 更新後タイトル */
                        title?: string;
                        /** @example true */
                        completed?: boolean;
                    };
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            todo: {
                                /** @example 1 */
                                id: string;
                                /** @example Vue.jsを学ぶ */
                                title: string;
                                /** @example false */
                                completed: boolean;
                                /** @example 2024-01-01T10:00:00Z */
                                createdAt: string;
                            };
                        };
                    };
                };
                /** @description バリデーションエラー */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success: boolean;
                            /** @example Todo not found */
                            message: string;
                        };
                    };
                };
                /** @description TODOが見つかりません */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success: boolean;
                            /** @example Todo not found */
                            message: string;
                        };
                    };
                };
            };
        };
        post?: never;
        /**
         * TODO削除
         * @description 指定IDのTODOを削除します（モックのため永続化されません）
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example Todo deleted */
                            message: string;
                        };
                    };
                };
                /** @description TODOが見つかりません */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success: boolean;
                            /** @example Todo not found */
                            message: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
